services:
  - type: web
    name: erpnext-installer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_installer.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
